# coding: utf-8

"""
    Unofficial Bungie.net API for Destiny 1

    These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lowlines89@gmail.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DestinyActivityModeType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DESTINY_ACTIVITY_MODE_TYPE__0 = "0"
    DESTINY_ACTIVITY_MODE_TYPE__2 = "2"
    DESTINY_ACTIVITY_MODE_TYPE__3 = "3"
    DESTINY_ACTIVITY_MODE_TYPE__4 = "4"
    DESTINY_ACTIVITY_MODE_TYPE__5 = "5"
    DESTINY_ACTIVITY_MODE_TYPE__6 = "6"
    DESTINY_ACTIVITY_MODE_TYPE__7 = "7"
    DESTINY_ACTIVITY_MODE_TYPE__9 = "9"
    DESTINY_ACTIVITY_MODE_TYPE__10 = "10"
    DESTINY_ACTIVITY_MODE_TYPE__11 = "11"
    DESTINY_ACTIVITY_MODE_TYPE__12 = "12"
    DESTINY_ACTIVITY_MODE_TYPE__13 = "13"
    DESTINY_ACTIVITY_MODE_TYPE__15 = "15"
    DESTINY_ACTIVITY_MODE_TYPE__16 = "16"
    DESTINY_ACTIVITY_MODE_TYPE__17 = "17"
    DESTINY_ACTIVITY_MODE_TYPE__18 = "18"
    DESTINY_ACTIVITY_MODE_TYPE__19 = "19"
    DESTINY_ACTIVITY_MODE_TYPE__20 = "20"
    DESTINY_ACTIVITY_MODE_TYPE__21 = "21"
    DESTINY_ACTIVITY_MODE_TYPE__22 = "22"
    DESTINY_ACTIVITY_MODE_TYPE__24 = "24"
    DESTINY_ACTIVITY_MODE_TYPE__25 = "25"
    DESTINY_ACTIVITY_MODE_TYPE__26 = "26"
    DESTINY_ACTIVITY_MODE_TYPE__27 = "27"
    DESTINY_ACTIVITY_MODE_TYPE__28 = "28"
    DESTINY_ACTIVITY_MODE_TYPE__29 = "29"
    DESTINY_ACTIVITY_MODE_TYPE__30 = "30"
    DESTINY_ACTIVITY_MODE_TYPE__31 = "31"
    DESTINY_ACTIVITY_MODE_TYPE__32 = "32"
    DESTINY_ACTIVITY_MODE_TYPE__37 = "37"
    DESTINY_ACTIVITY_MODE_TYPE__38 = "38"
    DESTINY_ACTIVITY_MODE_TYPE__39 = "39"
    DESTINY_ACTIVITY_MODE_TYPE__40 = "40"
    DESTINY_ACTIVITY_MODE_TYPE__41 = "41"
    DESTINY_ACTIVITY_MODE_TYPE__42 = "42"
    DESTINY_ACTIVITY_MODE_TYPE__43 = "43"
    DESTINY_ACTIVITY_MODE_TYPE__44 = "44"
    DESTINY_ACTIVITY_MODE_TYPE__45 = "45"
    DESTINY_ACTIVITY_MODE_TYPE__46 = "46"
    DESTINY_ACTIVITY_MODE_TYPE__47 = "47"
    DESTINY_ACTIVITY_MODE_TYPE__48 = "48"
    DESTINY_ACTIVITY_MODE_TYPE__49 = "49"
    DESTINY_ACTIVITY_MODE_TYPE__50 = "50"
    DESTINY_ACTIVITY_MODE_TYPE__51 = "51"
    DESTINY_ACTIVITY_MODE_TYPE__52 = "52"
    DESTINY_ACTIVITY_MODE_TYPE__53 = "53"
    DESTINY_ACTIVITY_MODE_TYPE__54 = "54"
    DESTINY_ACTIVITY_MODE_TYPE__55 = "55"
    DESTINY_ACTIVITY_MODE_TYPE__56 = "56"
    DESTINY_ACTIVITY_MODE_TYPE__57 = "57"
    DESTINY_ACTIVITY_MODE_TYPE__58 = "58"
    DESTINY_ACTIVITY_MODE_TYPE__59 = "59"
    DESTINY_ACTIVITY_MODE_TYPE__60 = "60"
    DESTINY_ACTIVITY_MODE_TYPE__61 = "61"
    DESTINY_ACTIVITY_MODE_TYPE__62 = "62"
    DESTINY_ACTIVITY_MODE_TYPE__63 = "63"
    DESTINY_ACTIVITY_MODE_TYPE__64 = "64"
    DESTINY_ACTIVITY_MODE_TYPE__65 = "65"
    DESTINY_ACTIVITY_MODE_TYPE__66 = "66"
    DESTINY_ACTIVITY_MODE_TYPE__67 = "67"
    DESTINY_ACTIVITY_MODE_TYPE__68 = "68"

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """DestinyActivityModeType - a model defined in OpenAPI"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DestinyActivityModeType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
