# coding: utf-8

"""
    Unofficial Bungie.net API for Destiny 1

    These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lowlines89@gmail.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineObject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'membership_type': 'BungieMembershipType',
        'item_reference_hash': 'int',
        'item_id': 'int',
        'stack_size': 'int',
        'character_id': 'int',
        'transfer_to_vault': 'bool'
    }

    attribute_map = {
        'membership_type': 'membershipType',
        'item_reference_hash': 'itemReferenceHash',
        'item_id': 'itemId',
        'stack_size': 'stackSize',
        'character_id': 'characterId',
        'transfer_to_vault': 'transferToVault'
    }

    def __init__(self, membership_type=None, item_reference_hash=None, item_id=None, stack_size=None, character_id=None, transfer_to_vault=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI"""  # noqa: E501

        self._membership_type = None
        self._item_reference_hash = None
        self._item_id = None
        self._stack_size = None
        self._character_id = None
        self._transfer_to_vault = None
        self.discriminator = None

        if membership_type is not None:
            self.membership_type = membership_type
        if item_reference_hash is not None:
            self.item_reference_hash = item_reference_hash
        if item_id is not None:
            self.item_id = item_id
        if stack_size is not None:
            self.stack_size = stack_size
        if character_id is not None:
            self.character_id = character_id
        if transfer_to_vault is not None:
            self.transfer_to_vault = transfer_to_vault

    @property
    def membership_type(self):
        """Gets the membership_type of this InlineObject.  # noqa: E501


        :return: The membership_type of this InlineObject.  # noqa: E501
        :rtype: BungieMembershipType
        """
        return self._membership_type

    @membership_type.setter
    def membership_type(self, membership_type):
        """Sets the membership_type of this InlineObject.


        :param membership_type: The membership_type of this InlineObject.  # noqa: E501
        :type: BungieMembershipType
        """

        self._membership_type = membership_type

    @property
    def item_reference_hash(self):
        """Gets the item_reference_hash of this InlineObject.  # noqa: E501

        The inventoryItemHash for an item.  # noqa: E501

        :return: The item_reference_hash of this InlineObject.  # noqa: E501
        :rtype: int
        """
        return self._item_reference_hash

    @item_reference_hash.setter
    def item_reference_hash(self, item_reference_hash):
        """Sets the item_reference_hash of this InlineObject.

        The inventoryItemHash for an item.  # noqa: E501

        :param item_reference_hash: The item_reference_hash of this InlineObject.  # noqa: E501
        :type: int
        """

        self._item_reference_hash = item_reference_hash

    @property
    def item_id(self):
        """Gets the item_id of this InlineObject.  # noqa: E501

        The instanceId of an equipable item. Should be \"0\" otherwise.  # noqa: E501

        :return: The item_id of this InlineObject.  # noqa: E501
        :rtype: int
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """Sets the item_id of this InlineObject.

        The instanceId of an equipable item. Should be \"0\" otherwise.  # noqa: E501

        :param item_id: The item_id of this InlineObject.  # noqa: E501
        :type: int
        """

        self._item_id = item_id

    @property
    def stack_size(self):
        """Gets the stack_size of this InlineObject.  # noqa: E501

        How many items to transfer. Should be \"1\" for equipable items.  # noqa: E501

        :return: The stack_size of this InlineObject.  # noqa: E501
        :rtype: int
        """
        return self._stack_size

    @stack_size.setter
    def stack_size(self, stack_size):
        """Sets the stack_size of this InlineObject.

        How many items to transfer. Should be \"1\" for equipable items.  # noqa: E501

        :param stack_size: The stack_size of this InlineObject.  # noqa: E501
        :type: int
        """

        self._stack_size = stack_size

    @property
    def character_id(self):
        """Gets the character_id of this InlineObject.  # noqa: E501

        A valid characterId that is associated with the given account.  # noqa: E501

        :return: The character_id of this InlineObject.  # noqa: E501
        :rtype: int
        """
        return self._character_id

    @character_id.setter
    def character_id(self, character_id):
        """Sets the character_id of this InlineObject.

        A valid characterId that is associated with the given account.  # noqa: E501

        :param character_id: The character_id of this InlineObject.  # noqa: E501
        :type: int
        """

        self._character_id = character_id

    @property
    def transfer_to_vault(self):
        """Gets the transfer_to_vault of this InlineObject.  # noqa: E501

        Move the item to or from the vault; true or false  # noqa: E501

        :return: The transfer_to_vault of this InlineObject.  # noqa: E501
        :rtype: bool
        """
        return self._transfer_to_vault

    @transfer_to_vault.setter
    def transfer_to_vault(self, transfer_to_vault):
        """Sets the transfer_to_vault of this InlineObject.

        Move the item to or from the vault; true or false  # noqa: E501

        :param transfer_to_vault: The transfer_to_vault of this InlineObject.  # noqa: E501
        :type: bool
        """

        self._transfer_to_vault = transfer_to_vault

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
